project_id = "hmmaubkxfewzlypywqff"

[functions.sync-client-pos]
verify_jwt = false

[functions.test-pos-connection]
verify_jwt = false

[functions.test-odoo-connection]
verify_jwt = false

[functions.notify-team]
verify_jwt = false

[functions.process-alerts]
verify_jwt = false

[functions.csp-violation-report]
verify_jwt = false

[functions.refresh-token-test]
verify_jwt = false

[functions.generate-certificate]
verify_jwt = false

[functions.send-certificate]
verify_jwt = false

[functions.course-recommendations]
verify_jwt = false

[functions.consumption-alerts]
verify_jwt = true

[functions.password-reset]
verify_jwt = false

[functions.validate-reset-token]
verify_jwt = false

[functions.update-password]
verify_jwt = false

[functions.test-email]
verify_jwt = false

[functions.send-barista-invitation]
verify_jwt = false

[functions.create-barista]
verify_jwt = false